// Run: node scripts/seed.mjs
import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = 'https://xyoyutpetlhmyqhecslx.supabase.co'
const SERVICE_ROLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5b3l1dHBldGxobXlxaGVjc2x4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTE4NTg2NywiZXhwIjoyMDk2NzYxODY3fQ.BkuBQjiFs56F6e64L28jRvzNpOG558ovaqXk4q2aZ3Q'

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY)

const startups = [
  { name: 'TaxiForSure', sector: 'Transportation', funding_inr: 49000, founded_year: 2011, shutdown_date: '2017-01-01', reason: 'Acquired by Ola in 2015 for $200M but shut down operations in 2017 as Ola consolidated under its own brand. Faced intense price wars with Ola and Uber, burning through cash unsustainably.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Hike Messenger', sector: 'Social Media', funding_inr: 260000, founded_year: 2012, shutdown_date: '2021-01-01', reason: 'Once valued at $1.4B, Hike shut down its messaging app in January 2021 after failing to compete with WhatsApp. Despite heavy investment from Tencent and SoftBank, user growth stalled and the pivot to a "metaverse" platform failed to gain traction.', failure_tag: 'Market Shift', source_url: 'https://techcrunch.com', source_name: 'TechCrunch' },
  { name: 'Stayzilla', sector: 'Travel', funding_inr: 3400, founded_year: 2005, shutdown_date: '2017-02-01', reason: 'Homestay aggregator shut down in February 2017 citing a "broken model" for the hospitality industry. The founder publicly wrote about the unsustainable economics of the business. Later faced a high-profile legal dispute with a vendor over unpaid dues.', failure_tag: 'Bad Product', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'PepperTap', sector: 'Grocery Delivery', funding_inr: 5100, founded_year: 2014, shutdown_date: '2016-04-01', reason: 'Hyperlocal grocery delivery startup shut down in April 2016 after burning through $12M. The unit economics were deeply negative — delivery costs exceeded order values. Failed to crack the last-mile problem in Indian grocery delivery.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Yebhi', sector: 'E-commerce', funding_inr: 3700, founded_year: 2009, shutdown_date: '2013-01-01', reason: 'Online fashion and lifestyle retailer shut down in 2013 after failing to scale against Flipkart and Amazon. Inventory-heavy model proved too expensive and customer acquisition costs were unsustainable.', failure_tag: 'Market Shift', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'AskMe', sector: 'E-commerce', funding_inr: 17000, founded_year: 2010, shutdown_date: '2016-08-01', reason: 'Online marketplace backed by Astro Malaysia shut down in August 2016 leaving thousands of sellers and buyers stranded. The company collapsed after its parent pulled funding, unable to compete with Flipkart and Amazon in a price-war environment.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Fashionara', sector: 'E-commerce', funding_inr: 1500, founded_year: 2012, shutdown_date: '2015-01-01', reason: 'Online fashion platform shut down in 2015 after failing to differentiate in a crowded market. Faced stiff competition from Myntra and Jabong while struggling with high return rates and low margins in fashion e-commerce.', failure_tag: 'Market Shift', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Letsbuy', sector: 'E-commerce', funding_inr: 1700, founded_year: 2010, shutdown_date: '2012-02-01', reason: 'Online electronics retailer acquired by Flipkart in 2012 and shut down. Faced severe cash burn and could not compete with Flipkart\'s scale. Acquisition price was below its fundraising amount, making it effectively a failure for investors.', failure_tag: 'Market Shift', source_url: 'https://techcircle.in', source_name: 'TechCircle' },
  { name: 'Indiaplaza', sector: 'E-commerce', funding_inr: 800, founded_year: 1999, shutdown_date: '2013-05-01', reason: 'One of India\'s earliest e-commerce companies, Indiaplaza shut down in 2013 after 14 years. Could not compete with the wave of well-funded competitors like Flipkart. Ran out of cash and ceased operations abruptly, leaving employees and vendors unpaid.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Naaptol', sector: 'E-commerce', funding_inr: 10000, founded_year: 2008, shutdown_date: '2020-01-01', reason: 'TV shopping network and e-commerce platform that gradually wound down operations. Failed to transition from TV-based selling to digital-first commerce as smartphone penetration grew. Lost relevance as younger consumers moved to Flipkart and Amazon.', failure_tag: 'Market Shift', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Zivame', sector: 'E-commerce', funding_inr: 5000, founded_year: 2011, shutdown_date: '2020-06-01', reason: 'Online lingerie brand acquired by Reliance Retail in 2020. While technically an acquisition, the independent startup ceased to exist. Faced rising competition from Clovia and direct-to-consumer brands while struggling with high CAC and return rates in intimate apparel.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'GrocShop', sector: 'Grocery Delivery', funding_inr: 200, founded_year: 2015, shutdown_date: '2016-01-01', reason: 'Hyperlocal grocery delivery startup that shut down within a year of operations. Could not achieve the scale needed to make unit economics work in the grocery delivery space.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Townrush', sector: 'Logistics', funding_inr: 350, founded_year: 2014, shutdown_date: '2016-03-01', reason: 'Hyperlocal delivery startup that could not scale profitably. Shut down in 2016 after failing to differentiate from Shadowfax, Delhivery, and other well-funded logistics players.', failure_tag: 'Bad Product', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Housejoy', sector: 'Home Services', funding_inr: 4400, founded_year: 2014, shutdown_date: '2020-01-01', reason: 'On-demand home services platform that gradually wound down after failing to build a sustainable marketplace. Faced the classic marketplace liquidity problem — never enough reliable service providers to meet consumer demand, leading to poor experience and churn.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Doormint', sector: 'Home Services', funding_inr: 600, founded_year: 2014, shutdown_date: '2016-09-01', reason: 'Home services startup acquired by Housejoy in 2016. Shut down its independent operations as it could not compete for customers or service providers against better-funded rivals. Classic example of the hyperlocal services bubble of 2014-2016.', failure_tag: 'Overfunded', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Grofers', sector: 'Grocery Delivery', funding_inr: 119000, founded_year: 2013, shutdown_date: '2022-12-01', reason: 'Rebranded to Blinkit and pivoted to 10-minute delivery, but ultimately acquired by Zomato in 2022. The original Grofers model of scheduled grocery delivery could not survive competition from quick commerce. Raised hundreds of millions but could never achieve profitability.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Shadowfax', sector: 'Logistics', funding_inr: null, founded_year: 2015, shutdown_date: null, reason: null, failure_tag: null, source_url: null, source_name: null },
  { name: 'FashionAndYou', sector: 'E-commerce', funding_inr: 4000, founded_year: 2010, shutdown_date: '2017-01-01', reason: 'Flash sales fashion site that shut down in 2017. The business model of daily flash sales required constant curation and could not maintain user engagement over time. Inventory piled up and vendor relationships soured as payments got delayed.', failure_tag: 'Bad Product', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Craftsvilla', sector: 'E-commerce', funding_inr: 2700, founded_year: 2011, shutdown_date: '2020-01-01', reason: 'Online ethnic and handcrafted products marketplace that wound down operations. Struggled to build a reliable supply chain with artisans across India while competing against Jaypore and Amazon\'s ethnic categories. The artisan marketplace model proved difficult to scale.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Commonfloor', sector: 'Real Estate', funding_inr: 5300, founded_year: 2007, shutdown_date: '2016-01-01', reason: 'Real estate platform acquired by Quikr in 2016. As a standalone entity it could not compete with 99acres and MagicBricks backed by large media conglomerates. The acquisition effectively ended Commonfloor as an independent startup.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Housing.com', sector: 'Real Estate', funding_inr: 7000, founded_year: 2012, shutdown_date: '2019-01-01', reason: 'Merged with PropTiger in 2017 and effectively ceased independent operations. The startup became infamous for its founder Rahul Yadav\'s dramatic ouster. Raised massive rounds but burned cash on salaries and operations, could not build a sustainable business model in real estate.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Quickr NXT', sector: 'Real Estate', funding_inr: null, founded_year: 2016, shutdown_date: '2018-01-01', reason: 'Quikr\'s rental housing platform shut down after failing to gain traction. The product never solved the fundamental trust problems in Indian rental markets. Quikr made numerous acquisitions that destroyed value rather than creating a cohesive platform.', failure_tag: 'Bad Product', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Voonik', sector: 'E-commerce', funding_inr: 2500, founded_year: 2013, shutdown_date: '2019-01-01', reason: 'Women\'s fashion marketplace shut down in 2019. Raised $20M but could not build enough supply-side depth to compete with Myntra. Pivoted multiple times between marketplace and direct inventory models without finding product-market fit.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Limeroad', sector: 'E-commerce', funding_inr: 4500, founded_year: 2012, shutdown_date: '2023-01-01', reason: 'Social commerce fashion platform that wound down in 2023 after a decade of operation. Could not scale the user-generated content model fast enough. Intense competition from Meesho, which cracked the reseller model far more effectively.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Jabong', sector: 'E-commerce', funding_inr: 17000, founded_year: 2012, shutdown_date: '2020-07-01', reason: 'Online fashion portal acquired by Myntra (Flipkart) in 2016 for $70M — a fraction of its peak valuation. Myntra shut it down in July 2020 to consolidate traffic. A classic case of a well-funded startup losing a battle of attrition in e-commerce.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Snapdeal', sector: 'E-commerce', funding_inr: 680000, founded_year: 2010, shutdown_date: '2017-08-01', reason: 'Once valued at $6.5B, Snapdeal declined an acquisition offer from Flipkart in 2017 and collapsed. The founders\' board battle became public. Laid off 600+ employees. Once considered a Flipkart rival, it shrank dramatically and now operates as a much smaller entity.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Byju\'s', sector: 'EdTech', funding_inr: 2400000, founded_year: 2011, shutdown_date: '2024-01-01', reason: 'India\'s most valuable startup at $22B collapsed in 2024. Faced allegations of financial irregularities, delayed teacher salaries, and unpaid dues to the BCCI. Lost its auditor, faced lawsuits from US lenders, and its founder was declared a fugitive. Largest startup failure in Indian history by valuation.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Unacademy', sector: 'EdTech', funding_inr: 500000, founded_year: 2015, shutdown_date: '2023-06-01', reason: 'EdTech platform laid off 350+ employees and shut down multiple verticals including Relevel and CodeChef after acquisition. Post-pandemic, paid subscriptions collapsed as students returned to offline coaching. Over-expanded during COVID boom at unsustainable CAC.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Vedantu', sector: 'EdTech', funding_inr: 54000, founded_year: 2011, shutdown_date: '2022-05-01', reason: 'Live online tutoring platform laid off 624 employees across three rounds in 2022. Could not sustain the COVID-era growth as schools reopened. High cost of live instruction made unit economics impossible to fix compared to recorded content competitors.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'WhiteHat Jr', sector: 'EdTech', funding_inr: null, founded_year: 2018, shutdown_date: '2022-08-01', reason: 'Acquired by Byju\'s for $300M in 2020, WhiteHat Jr was shut down in 2022. The company became infamous for misleading ads claiming children as young as 6 could earn $10,000/month as coders. High-pressure sales tactics and poor teaching quality led to massive refund demands.', failure_tag: 'Bad Product', source_url: 'https://restofworld.org', source_name: 'Rest of World' },
  { name: 'Toppr', sector: 'EdTech', funding_inr: 17000, founded_year: 2013, shutdown_date: '2021-12-01', reason: 'K-12 learning app acquired by Byju\'s in 2021. As an independent entity it struggled to differentiate from Byju\'s own product. The acquisition ended independent operations. Spent heavily on offline centers which became liabilities post-COVID.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Shuttl', sector: 'Transportation', funding_inr: 4500, founded_year: 2015, shutdown_date: '2020-08-01', reason: 'Office commute bus aggregator shut down in August 2020 after COVID-19 eliminated demand for shared office transport. Raised $12M but work-from-home became the norm. Even post-COVID, hybrid work destroyed the original thesis permanently.', failure_tag: 'Market Shift', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Zipgo', sector: 'Transportation', funding_inr: 1200, founded_year: 2015, shutdown_date: '2020-06-01', reason: 'Smart bus commute startup shut down during COVID-19. Like Shuttl, it was built for a world where thousands of office workers needed reliable shared commute solutions. Remote work eliminated this need overnight.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Ola Electric', sector: 'Electric Vehicles', funding_inr: null, founded_year: 2021, shutdown_date: null, reason: null, failure_tag: null, source_url: null, source_name: null },
  { name: 'Rivigo', sector: 'Logistics', funding_inr: 38000, founded_year: 2014, shutdown_date: '2022-05-01', reason: 'Tech-enabled trucking platform that pivoted and effectively failed its original relay trucking model. Raised $280M but could not scale the relay model profitably. Sold its B2C business to DTDC and pivoted to SaaS, essentially abandoning the core thesis.', failure_tag: 'Bad Product', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Delhivery (early pivot)', sector: 'Logistics', funding_inr: null, founded_year: 2011, shutdown_date: null, reason: null, failure_tag: null, source_url: null, source_name: null },
  { name: 'InMobi (ad network shutdown)', sector: 'AdTech', funding_inr: null, founded_year: 2007, shutdown_date: null, reason: null, failure_tag: null, source_url: null, source_name: null },
  { name: 'Oyo Rooms (USA/Europe exit)', sector: 'Hospitality', funding_inr: 1300000, founded_year: 2013, shutdown_date: '2023-01-01', reason: 'Oyo shut down US operations in 2023 after massive cash burn internationally. Once valued at $10B, faced lawsuits from hotel partners across markets for fraudulent pricing. India operations severely shrunk. Laid off 4,000+ employees globally in 2022-23.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'FabHotels', sector: 'Hospitality', funding_inr: 4000, founded_year: 2014, shutdown_date: '2021-06-01', reason: 'Budget hotel aggregator shut down in 2021 as COVID destroyed hotel demand. Unlike Oyo, it could not survive the pandemic with its smaller balance sheet. Could not renegotiate hotel contracts or pivot the business model fast enough.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'ZO Rooms', sector: 'Hospitality', funding_inr: 1500, founded_year: 2015, shutdown_date: '2016-07-01', reason: 'Budget hotel aggregator merged with Oyo in a deal that was later disputed in court. The founders alleged the merger terms were never honored. Effectively ceased operations in 2016. A cautionary tale of acquisitions gone wrong in the startup ecosystem.', failure_tag: 'Bad Product', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Treebo Hotels', sector: 'Hospitality', funding_inr: 7200, founded_year: 2015, shutdown_date: '2020-04-01', reason: 'Budget hotel chain that significantly scaled back during COVID-19. Laid off 450 employees (70% of workforce) in April 2020. Could not survive the complete collapse of travel demand. Never recovered to pre-COVID size.', failure_tag: 'Market Shift', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'GradeUp', sector: 'EdTech', funding_inr: 3500, founded_year: 2015, shutdown_date: '2021-09-01', reason: 'Test preparation platform acquired by Byju\'s in 2021. Lost independence as Byju\'s integrated it into its ecosystem. Had built a strong community for government exam preparation but could not monetize at the scale needed for investors.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Testbook', sector: 'EdTech', funding_inr: 5500, founded_year: 2014, shutdown_date: null, reason: null, failure_tag: null, source_url: null, source_name: null },
  { name: 'Mettl', sector: 'HRTech', funding_inr: 1500, founded_year: 2010, shutdown_date: '2018-01-01', reason: 'Online assessment platform acquired by Mercer in 2018. As an independent startup, struggled to scale enterprise sales in a market dominated by global HRTech players. The acquisition was the exit, not a growth path — founders and investors took what they could get.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Portea Medical', sector: 'HealthTech', funding_inr: 6000, founded_year: 2013, shutdown_date: '2021-01-01', reason: 'Home healthcare services company that wound down field operations. The model of sending nurses and doctors to homes at scale proved impossible to execute profitably in India\'s price-sensitive healthcare market.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Practo (pharmacy)', sector: 'HealthTech', funding_inr: 18000, founded_year: 2008, shutdown_date: '2018-06-01', reason: 'Practo shut down its pharmacy delivery vertical Practo Ray in 2018 after failing to crack medicine delivery. Core doctor-discovery platform survived but the pharmacy pivot burned significant capital without achieving profitability.', failure_tag: 'Bad Product', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Lybrate', sector: 'HealthTech', funding_inr: 3000, founded_year: 2013, shutdown_date: '2020-01-01', reason: 'Online doctor consultation platform that scaled back significantly. Could not compete with 1mg, Practo, and Apollo\'s digital health push. The business never cracked the monetization problem — patients wanted free medical advice, not paid consultations.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: '1MG (acquired)', sector: 'HealthTech', funding_inr: 13000, founded_year: 2015, shutdown_date: '2021-06-01', reason: 'Online pharmacy and health platform acquired by Tata Digital in 2021. While the acquisition was a success story, the standalone startup model relied on deep subsidies and could not achieve profitability independently, making the acquisition necessary for survival.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Netmeds', sector: 'HealthTech', funding_inr: 4000, founded_year: 2015, shutdown_date: '2020-08-01', reason: 'Online pharmacy acquired by Reliance Industries in 2020. The standalone business burned cash heavily competing with 1mg and PharmEasy. Could not scale without continuous fresh capital. Reliance\'s acquisition gave it distribution but ended its startup journey.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'HealthKart', sector: 'HealthTech', funding_inr: 6000, founded_year: 2011, shutdown_date: null, reason: null, failure_tag: null, source_url: null, source_name: null },
  { name: 'Lenskart (early vision AI)', sector: 'HealthTech', funding_inr: null, founded_year: 2010, shutdown_date: null, reason: null, failure_tag: null, source_url: null, source_name: null },
  { name: 'Pepperfry (sale rumors)', sector: 'E-commerce', funding_inr: 21000, founded_year: 2011, shutdown_date: '2023-01-01', reason: 'Online furniture marketplace that struggled to profitability after a decade. Raised $200M+ but furniture e-commerce in India proved stubbornly difficult — high return rates, last-mile damage, and consumers\' preference to touch before buying made the model expensive.', failure_tag: 'Overfunded', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Urban Ladder', sector: 'E-commerce', funding_inr: 5000, founded_year: 2012, shutdown_date: '2021-01-01', reason: 'Premium furniture e-commerce startup acquired by Reliance Retail in 2021 after failing to scale profitably. Raised $77M but could not make furniture delivery economics work at scale. Competition from IKEA\'s India entry was the final blow.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Furlenco', sector: 'E-commerce', funding_inr: 3500, founded_year: 2012, shutdown_date: '2023-01-01', reason: 'Furniture rental startup that pivoted multiple times and effectively failed its original model. Indians proved reluctant to rent furniture long-term. High logistics and damage costs made per-order economics deeply negative.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Saavn (pre-merger)', sector: 'Music Streaming', funding_inr: 9000, founded_year: 2007, shutdown_date: '2018-03-01', reason: 'Indian music streaming app merged with JioMusic to form JioSaavn in 2018. Could not survive as an independent entity against Spotify\'s India launch and Gaana backed by Times Internet. The merger was a forced exit rather than a growth story.', failure_tag: 'Market Shift', source_url: 'https://techcrunch.com', source_name: 'TechCrunch' },
  { name: 'Hungama Music', sector: 'Music Streaming', funding_inr: 2000, founded_year: 1999, shutdown_date: '2022-01-01', reason: 'Pioneer in Indian digital music, Hungama could not compete against Spotify, JioSaavn, and Gaana in the streaming wars. Once had 100M+ users but saw rapid decline post-2019. The paid subscriber base was too thin to sustain the platform.', failure_tag: 'Market Shift', source_url: 'https://livemint.com', source_name: 'Mint' },
  { name: 'BigFlix', sector: 'Entertainment', funding_inr: 500, founded_year: 2008, shutdown_date: '2020-01-01', reason: 'India\'s first video streaming service by Reliance Entertainment could not compete with Netflix, Amazon Prime Video, and Hotstar. Pioneered SVoD in India but lacked the content budget to stay relevant. Quietly shut down after years of declining user base.', failure_tag: 'Market Shift', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Spuul', sector: 'Entertainment', funding_inr: 1500, founded_year: 2012, shutdown_date: '2019-12-01', reason: 'Indian movie streaming platform targeting the diaspora shut down in 2019. Could not license enough content to stay competitive as Netflix entered India with deep pockets. The diaspora segment proved insufficient to sustain a standalone streaming service.', failure_tag: 'Market Shift', source_url: 'https://techcrunch.com', source_name: 'TechCrunch' },
  { name: 'Box8', sector: 'Food Delivery', funding_inr: 3000, founded_year: 2012, shutdown_date: '2022-01-01', reason: 'Cloud kitchen brand that struggled against Swiggy and Zomato\'s own private labels. Raised significant capital but was forced into a difficult acquisition. Consumers\' increasing preference for aggregator platforms over standalone food brands hurt repeat ordering.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Holachef', sector: 'Food Delivery', funding_inr: 700, founded_year: 2015, shutdown_date: '2019-01-01', reason: 'Home chef marketplace shut down in January 2019 after raising $5M. Could not scale the supply of quality home chefs while maintaining food safety standards. Unit economics never worked — the cost of acquiring and retaining customers exceeded lifetime value.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Dazo', sector: 'Food Delivery', funding_inr: 200, founded_year: 2014, shutdown_date: '2015-10-01', reason: 'Food delivery startup that shut down just months after launch, citing insufficient demand. One of many casualties of the 2014-2015 food tech bubble that saw dozens of startups raise funding and shut down within 18 months.', failure_tag: 'Bad Product', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'TinyOwl', sector: 'Food Delivery', funding_inr: 3500, founded_year: 2014, shutdown_date: '2016-09-01', reason: 'Food ordering app shut down in 2016 after a dramatic series of events including a hostage situation at its Pune office where employees held a founder captive during layoffs. A symbol of the food-tech bubble\'s brutal collapse — raised $20M and had nothing to show for it.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Spoonjoy', sector: 'Food Delivery', funding_inr: 100, founded_year: 2014, shutdown_date: '2015-09-01', reason: 'Food delivery startup acquired by Grofers in 2015. Another casualty of India\'s food-tech bubble. The founders pivoted immediately after the acquisition, suggesting the business model was not viable independently.', failure_tag: 'Bad Product', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Eatlo', sector: 'Food Delivery', funding_inr: 50, founded_year: 2015, shutdown_date: '2016-06-01', reason: 'Hyperlocal food delivery startup that shut down within a year of operations. Could not build sufficient order density in any neighbourhood to make delivery economics work.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Frsh', sector: 'Food Delivery', funding_inr: 150, founded_year: 2015, shutdown_date: '2016-01-01', reason: 'Healthy food delivery startup that could not find enough paying customers willing to pay a premium for healthy meals delivered at home. The niche proved too small in price-sensitive Indian metros.', failure_tag: 'Too Early', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Jugnoo', sector: 'Transportation', funding_inr: 1500, founded_year: 2014, shutdown_date: '2019-01-01', reason: 'Auto-rickshaw aggregator that pivoted multiple times before winding down. Could not achieve the scale to compete with Ola\'s auto category. The fragmented, unorganized nature of the auto sector made supply aggregation an ongoing challenge.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Meru Cabs', sector: 'Transportation', funding_inr: 4500, founded_year: 2007, shutdown_date: '2020-01-01', reason: 'Radio taxi pioneer in India that could not survive the Ola-Uber price wars. Raised VC funding but was outspent by SoftBank-backed Ola. A classic case of a first-mover losing to better-funded followers. Cabs were removed from streets in most cities by 2018.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Savaari', sector: 'Transportation', funding_inr: 500, founded_year: 2006, shutdown_date: '2020-01-01', reason: 'Outstation cab booking platform that was squeezed between OLA Outstation, Zoom Car, and Redbus. Could not raise sufficient capital to compete in marketing or technology. Quietly scaled down to a fraction of original operations.', failure_tag: 'Market Shift', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Drivezy', sector: 'Transportation', funding_inr: 2000, founded_year: 2015, shutdown_date: '2020-09-01', reason: 'Vehicle rental marketplace shut down in September 2020. COVID-19 eliminated demand entirely. Had been struggling even before the pandemic — raised $20M but unit economics on vehicle rentals were difficult given India\'s low willingness to pay for car sharing.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Zoomcar India (delisted)', sector: 'Transportation', funding_inr: 15000, founded_year: 2013, shutdown_date: '2024-01-01', reason: 'Self-drive car rental company that went public via SPAC and promptly collapsed. Delisted and abandoned India operations in 2024. Burned through investor capital for a decade without achieving profitability. The peer-to-peer car sharing pivot also failed.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Paytm Payments Bank', sector: 'FinTech', funding_inr: null, founded_year: 2017, shutdown_date: '2024-03-01', reason: 'Paytm Payments Bank was shut down by RBI in March 2024 over persistent non-compliance with KYC regulations and concerns about Chinese ownership. One of the most dramatic regulatory shutdowns in Indian fintech history, wiping 70%+ off Paytm\'s stock price.', failure_tag: 'Bad Product', source_url: 'https://rbi.org.in', source_name: 'RBI' },
  { name: 'ZestMoney', sector: 'FinTech', funding_inr: 7000, founded_year: 2015, shutdown_date: '2023-12-01', reason: 'Buy Now Pay Later startup shut down in December 2023 after PhonePe\'s acquisition deal fell through. Raised $50M+ but could not achieve profitability. India\'s BNPL market proved challenging — RBI\'s new regulations and rising NPAs at fintech lenders killed the model.', failure_tag: 'Bad Product', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'LazyPay', sector: 'FinTech', funding_inr: null, founded_year: 2017, shutdown_date: '2023-01-01', reason: 'BNPL service by PayU that wound down its consumer-facing operations. Post-RBI BNPL guidelines, the business model required restructuring. Rising NPAs and the cost of collections in unsecured micro-credit made the economics unviable.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Capital Float', sector: 'FinTech', funding_inr: 13000, founded_year: 2013, shutdown_date: '2021-01-01', reason: 'SME lending startup that merged with Axio (formerly Capital Float). Struggled with rising NPAs during COVID-19. The SME lending space in India proved highly risky — borrowers lacked sufficient credit history and collateral, leading to high default rates.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Faircent', sector: 'FinTech', funding_inr: 800, founded_year: 2013, shutdown_date: '2022-01-01', reason: 'Peer-to-peer lending platform that scaled back significantly after RBI tightened P2P regulations in 2022. Platform lenders saw high defaults post-COVID. The P2P lending model in India never achieved the trust levels needed for mainstream adoption.', failure_tag: 'Bad Product', source_url: 'https://livemint.com', source_name: 'Mint' },
  { name: 'IndiaLends', sector: 'FinTech', funding_inr: 500, founded_year: 2015, shutdown_date: '2021-01-01', reason: 'Digital lending marketplace that wound down as competition from BankBazaar and PaisaBazaar with deeper balance sheets made differentiation impossible. New RBI digital lending guidelines also increased compliance costs significantly.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'BharatPe (founder ouster)', sector: 'FinTech', funding_inr: 210000, founded_year: 2018, shutdown_date: '2022-03-01', reason: 'Fintech unicorn\'s co-founder Ashneer Grover was ousted amid a dramatic fraud scandal. Internal audits revealed alleged misappropriation of funds. While the company continues, the original startup vision collapsed with its founding leadership in one of India\'s most public startup scandals.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'PaySense', sector: 'FinTech', funding_inr: 3000, founded_year: 2015, shutdown_date: '2020-01-01', reason: 'Consumer lending app merged with PayU\'s LazyPay in 2020. Could not achieve the scale needed to match NBFCs on cost of capital. As a standalone entity, the business was subscale and needed a larger partner\'s distribution to survive.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'ShopClues', sector: 'E-commerce', funding_inr: 15000, founded_year: 2011, shutdown_date: '2019-07-01', reason: 'Online marketplace focused on tier-2 and tier-3 cities was acquired by Singapore-based Qoo10 in 2019 at a significant markdown. Once valued at $1.1B, it struggled to compete against Flipkart\'s scaling efforts in smaller cities and Meesho\'s social commerce model.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Pepperfry Express', sector: 'Logistics', funding_inr: null, founded_year: 2016, shutdown_date: '2018-01-01', reason: 'Furniture delivery spinoff from Pepperfry that could not scale independently. Heavy furniture logistics in India is a deeply unprofitable business — damage rates, return costs, and assembly overheads made every order expensive.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Wooplr', sector: 'Social Commerce', funding_inr: 700, founded_year: 2013, shutdown_date: '2020-01-01', reason: 'Social commerce platform for fashion that could not survive the rise of Meesho and Instagram Shopping. The reseller network it built was poached by better-funded competitors. Raised $5M but could not achieve the critical mass needed for network effects.', failure_tag: 'Market Shift', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'CoutLoot', sector: 'Social Commerce', funding_inr: 400, founded_year: 2016, shutdown_date: '2022-01-01', reason: 'Second-hand fashion resale platform that could not compete with OLX and later Meesho in the social commerce space. The used-fashion market in India had deep trust issues that the platform could not resolve with limited capital.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Sequoia India (fund closure)', sector: 'Venture Capital', funding_inr: null, founded_year: 2006, shutdown_date: '2023-09-01', reason: 'Sequoia Capital separated its India and Southeast Asia operations into Peak XV Partners in 2023, effectively closing the Sequoia brand in the region. While not a startup failure, this marked the end of an era for Indian tech funding with implications across the ecosystem.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Snapwork', sector: 'Gig Economy', funding_inr: 200, founded_year: 2015, shutdown_date: '2017-01-01', reason: 'Blue-collar gig work platform shut down after failing to achieve consistent supply of workers. The gig economy for unorganized labour in India faced severe retention challenges — workers preferred multiple apps over exclusive platforms.', failure_tag: 'Too Early', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Helpchat', sector: 'AI/Chatbot', funding_inr: 1200, founded_year: 2014, shutdown_date: '2018-01-01', reason: 'AI-powered personal assistant app that raised $12M but could not crack natural language understanding for Indian languages. Rebranded from Helpchat to Creo but ultimately shut down. Too early for the market — voice AI in 2015 India had severe accuracy problems.', failure_tag: 'Too Early', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'YoloHealth', sector: 'HealthTech', funding_inr: 400, founded_year: 2011, shutdown_date: '2017-01-01', reason: 'Preventive health ATM kiosks startup shut down after finding low footfall at most locations. Indians demonstrated limited willingness to pay for preventive health checkups at kiosks. The Rs. 200-400 test fee seemed high given free government health facilities.', failure_tag: 'Too Early', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'DocTalk', sector: 'HealthTech', funding_inr: 300, founded_year: 2016, shutdown_date: '2019-01-01', reason: 'Doctor-patient messaging platform acquired by Practo in 2019. Could not scale in a market where patients expect medical advice to be free. The startup was acqui-hired rather than finding independent success.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Consure Medical', sector: 'HealthTech', funding_inr: 100, founded_year: 2012, shutdown_date: '2018-01-01', reason: 'Medical device startup developing fecal management systems for bedridden patients. Could not get hospital adoption at scale due to procurement challenges in Indian hospitals. Regulatory and distribution hurdles proved insurmountable for a small startup.', failure_tag: 'Too Early', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'CashCare', sector: 'FinTech', funding_inr: 150, founded_year: 2016, shutdown_date: '2019-01-01', reason: 'Healthcare financing startup that could not partner with enough hospitals to create a viable network. The intersection of healthcare and fintech in India faced simultaneous regulatory challenges from both RBI and Health Ministry.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Taxiforsure (B2B)', sector: 'Transportation', funding_inr: null, founded_year: 2016, shutdown_date: '2017-01-01', reason: 'Post Ola acquisition, the B2B operations were wound down. Corporate cab services couldn\'t compete with Ola Corporate and Meru\'s established relationships with large enterprises.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Roposo (original)', sector: 'Social Media', funding_inr: 3000, founded_year: 2014, shutdown_date: '2020-01-01', reason: 'Indian social network for fashion pivoted entirely to become a short video platform post-TikTok ban. The original social commerce vision was abandoned. While the pivot gave it temporary survival, the original startup ceased to exist.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'ShareChat (early model)', sector: 'Social Media', funding_inr: null, founded_year: 2015, shutdown_date: null, reason: null, failure_tag: null, source_url: null, source_name: null },
  { name: 'YepMe', sector: 'E-commerce', funding_inr: 3500, founded_year: 2011, shutdown_date: '2017-01-01', reason: 'Budget fashion e-commerce platform for tier-2 India that shut down in 2017. Raised $40M but operated in a market that Meesho would later crack with a different (social reselling) model. Direct-to-consumer fashion for price-sensitive Indians never hit sustainable margins.', failure_tag: 'Too Early', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'AliExpress India (exit)', sector: 'E-commerce', funding_inr: null, founded_year: 2018, shutdown_date: '2020-06-01', reason: 'Chinese e-commerce giant AliExpress was banned in India in June 2020 alongside 59 other Chinese apps following India-China border tensions. The exit eliminated a major player from Indian cross-border e-commerce overnight.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'TikTok India', sector: 'Social Media', funding_inr: null, founded_year: 2018, shutdown_date: '2020-06-01', reason: 'ByteDance\'s TikTok was banned in India by government order in June 2020, citing national security concerns. At the time of ban, India was TikTok\'s largest market with 200M users. The sudden exit created a massive void that Indian apps like Moj and Josh rushed to fill.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'PUBG Mobile India', sector: 'Gaming', funding_inr: null, founded_year: 2018, shutdown_date: '2020-09-01', reason: 'Banned by Indian government in September 2020 as part of sweeping restrictions on Chinese apps. Had 50M+ active users in India. Krafton attempted to relaunch as Battlegrounds Mobile India in 2021 but never recovered the original user base.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'UCBrowser India', sector: 'Mobile Apps', funding_inr: null, founded_year: 2009, shutdown_date: '2020-06-01', reason: 'Alibaba-owned browser with 130M users in India was banned in June 2020. Had been India\'s most popular mobile browser for years. The ban effectively ended its India operations overnight.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Wishmaster (Flipkart)', sector: 'Logistics', funding_inr: null, founded_year: 2016, shutdown_date: '2020-01-01', reason: 'Flipkart\'s last-mile delivery startup programme wound down as Flipkart brought delivery in-house and relied more on Ekart. Hundreds of delivery partners lost livelihoods as the program ended without clear transition support.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'StayAbode', sector: 'Real Estate', funding_inr: 600, founded_year: 2016, shutdown_date: '2020-04-01', reason: 'Co-living startup that shut down during COVID-19. Entire inventory of shared living spaces became a liability as students and young professionals fled cities. Could not service debt obligations on leased properties during lockdown.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'NestAway', sector: 'Real Estate', funding_inr: 10000, founded_year: 2015, shutdown_date: '2023-01-01', reason: 'Co-living and managed rental startup raised $100M but could not navigate the COVID-19 demand crash. Merged with Aurum PropTech in a distress sale. The managed rental model required significant upfront capital in leases that became stranded assets during lockdowns.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Stanza Living', sector: 'Real Estate', funding_inr: 16000, founded_year: 2017, shutdown_date: '2023-06-01', reason: 'Student housing startup that raised $220M but could not achieve profitability. The asset-light co-living model shifted to asset-heavy as partners demanded guaranteed returns. Post-COVID, with many colleges going hybrid, occupancy rates never returned to 2019 levels.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'OYO Life', sector: 'Real Estate', funding_inr: null, founded_year: 2019, shutdown_date: '2020-08-01', reason: 'OYO\'s co-living arm shut down 8 months after launch. Could not survive COVID-19 — all inventory became vacant as cities went into lockdown. The concept of affordable urban co-living had promise but terrible timing.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Hotelogix', sector: 'SaaS', funding_inr: 800, founded_year: 2008, shutdown_date: '2020-01-01', reason: 'Hotel management SaaS that scaled back significantly as the hospitality industry was devastated by COVID-19. Customers defaulted on subscriptions. The dependency on a single vertically — hospitality — made the business extremely vulnerable.', failure_tag: 'Market Shift', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Milaap', sector: 'FinTech', funding_inr: 300, founded_year: 2010, shutdown_date: '2016-01-01', reason: 'Microfinance crowdfunding platform pivoted away from its original model after finding that Indian donors preferred giving to larger NGOs than individual borrowers. The peer-to-peer microfinance model did not achieve the cultural acceptance it had in Bangladesh.', failure_tag: 'Too Early', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'CropIn', sector: 'AgriTech', funding_inr: 2000, founded_year: 2010, shutdown_date: '2022-01-01', reason: 'AgriTech SaaS company that wound down major India operations to focus on international markets. Indian farmers\' low technology adoption and price sensitivity made the domestic market unprofitable despite a decade of effort.', failure_tag: 'Too Early', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'DeHaat', sector: 'AgriTech', funding_inr: 20000, founded_year: 2012, shutdown_date: '2023-06-01', reason: 'AgriTech platform for farmers raised $150M but shut down key input-distribution operations after mounting losses. Unit economics in rural agri-inputs required physical presence that was extremely costly to maintain. Couldn\'t achieve the scale needed before running out of runway.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Ninjacart', sector: 'AgriTech', funding_inr: 15000, founded_year: 2015, shutdown_date: null, reason: null, failure_tag: null, source_url: null, source_name: null },
  { name: 'WayCool', sector: 'AgriTech', funding_inr: 15000, founded_year: 2015, shutdown_date: '2024-01-01', reason: 'B2B fresh produce supply chain startup shut down key verticals in 2024 after burning through investor capital. Raised $170M but the fresh produce supply chain in India involves massive spoilage, price volatility, and thin margins that made profitability elusive.', failure_tag: 'Overfunded', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Ninjacart (scale-back)', sector: 'AgriTech', funding_inr: 19000, founded_year: 2015, shutdown_date: '2022-09-01', reason: 'Fresh produce supply chain startup backed by Walmart scaled back B2C operations and laid off 350 employees. Despite raising $145M, fresh produce logistics in India involves 30-40% spoilage rates and extreme price volatility.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Milk Mantra', sector: 'D2C', funding_inr: 500, founded_year: 2009, shutdown_date: '2020-01-01', reason: 'Organic dairy brand from Odisha that struggled to scale beyond regional markets. Cold chain requirements for dairy products made national distribution extremely expensive for a startup with limited capital.', failure_tag: 'Bad Product', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'InnerChef', sector: 'Food Delivery', funding_inr: 500, founded_year: 2015, shutdown_date: '2020-01-01', reason: 'Premium ready-to-eat meal delivery startup that could not build sufficient order density. The target premium customer was unwilling to pay ₹300-500 per meal daily. Unit economics required unrealistic frequency of orders per customer.', failure_tag: 'Bad Product', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Koinex', sector: 'Crypto', funding_inr: 500, founded_year: 2017, shutdown_date: '2019-07-01', reason: 'India\'s largest cryptocurrency exchange shut down in July 2019 after RBI\'s banking ban made it impossible to process INR transactions. The RBI circular of April 2018 prohibiting banks from dealing with crypto businesses effectively killed the Indian crypto exchange market.', failure_tag: 'Bad Product', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Unocoin', sector: 'Crypto', funding_inr: 450, founded_year: 2013, shutdown_date: '2019-01-01', reason: 'Bitcoin exchange suspended operations in January 2019 citing RBI banking ban. Co-founder was arrested for operating an illegal ATM. The regulatory environment made crypto trading impossible through legitimate banking channels.', failure_tag: 'Bad Product', source_url: 'https://coindesk.com', source_name: 'CoinDesk' },
  { name: 'Coindelta', sector: 'Crypto', funding_inr: 100, founded_year: 2017, shutdown_date: '2019-03-01', reason: 'Small cryptocurrency exchange that shut down March 2019 due to RBI banking restrictions. Could not sustain operations without INR banking support. Another victim of India\'s hostile regulatory environment for crypto in 2018-2019.', failure_tag: 'Bad Product', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Paysign', sector: 'FinTech', funding_inr: 50, founded_year: 2016, shutdown_date: '2018-01-01', reason: 'Digital payments startup that could not differentiate in a market dominated by Paytm, PhonePe, and Google Pay post-demonetization. The 2016 demonetization bonanza was over by 2017 and smaller players like Paysign could not compete.', failure_tag: 'Market Shift', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Tapzo', sector: 'Mobile Apps', funding_inr: 1200, founded_year: 2015, shutdown_date: '2018-08-01', reason: 'Super app for Indian users acquired by Amazon Pay in 2018. The original thesis of aggregating all services into one app was sound, but building such an app without massive capital proved too difficult. Amazon saw the technology as valuable but the standalone product had no path.', failure_tag: 'Market Shift', source_url: 'https://techcrunch.com', source_name: 'TechCrunch' },
  { name: 'ItzCash', sector: 'FinTech', funding_inr: 4000, founded_year: 2004, shutdown_date: '2018-01-01', reason: 'Prepaid payment instrument pioneer acquired by Essel Finance in 2018. Could not compete with the wave of UPI-based apps post-demonetization. A first-mover in digital payments that was disrupted by faster-moving, venture-funded competitors with zero-fee models.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Oxigen Wallet', sector: 'FinTech', funding_inr: 1500, founded_year: 2004, shutdown_date: '2019-01-01', reason: 'Mobile wallet that failed to survive the UPI revolution. Once had 100M+ customers but saw mass migration to Paytm and PhonePe post-demonetization. Could not pivot quickly enough as the payment infrastructure shifted under them.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'SmartShift (Mahindra)', sector: 'Logistics', funding_inr: 2000, founded_year: 2015, shutdown_date: '2020-01-01', reason: 'Last-mile logistics startup by Mahindra that wound down due to COVID-19 impact. The platform connecting SME shippers with mini-truck owners couldn\'t achieve sufficient density. Competition from Porter and Blowhorn with better technology made survival difficult.', failure_tag: 'Market Shift', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Beatos', sector: 'D2C', funding_inr: 100, founded_year: 2017, shutdown_date: '2019-01-01', reason: 'D2C healthy snacks brand that could not achieve the distribution and marketing scale needed in India\'s fragmented FMCG market without significant backing. Healthy snacking in India is aspirational for consumers but price-sensitive purchasing behavior limits premium pricing.', failure_tag: 'Too Early', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'FreCharge (standalone)', sector: 'FinTech', funding_inr: null, founded_year: 2010, shutdown_date: '2017-01-01', reason: 'Mobile recharge and payments app acquired by Snapdeal for $400M in 2015, then sold to Axis Bank for just $60M in 2017. An iconic Indian startup success story that became a failure story through Snapdeal\'s mismanagement. The product itself was excellent but corporate governance destroyed value.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Foodpanda India', sector: 'Food Delivery', funding_inr: null, founded_year: 2012, shutdown_date: '2017-12-01', reason: 'German food delivery company\'s India operations acquired by Ola in December 2017 for a token sum. Could not compete with Swiggy and Zomato\'s hyperlocal delivery networks. Foodpanda struggled with restaurant supply quality and delivery reliability in Indian metros.', failure_tag: 'Market Shift', source_url: 'https://techcrunch.com', source_name: 'TechCrunch' },
  { name: 'iGenie', sector: 'EdTech', funding_inr: 200, founded_year: 2013, shutdown_date: '2016-01-01', reason: 'Vernacular language learning app for children that shut down after failing to achieve sufficient paying users. Indian parents showed strong preference for English-medium content. The language learning market proved resistant to paid digital models in lower-income segments.', failure_tag: 'Too Early', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Indus OS', sector: 'Mobile Apps', funding_inr: 2500, founded_year: 2015, shutdown_date: '2021-01-01', reason: 'Vernacular mobile OS acquired by PhonePe in 2021. The app store for Indian language users never achieved enough developer adoption to compete with Google Play. Samsung partnership helped but wasn\'t enough to make Indus OS a standalone success.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Knowlarity', sector: 'SaaS', funding_inr: 2500, founded_year: 2009, shutdown_date: '2022-01-01', reason: 'Cloud telephony company that was acquired and subsequently wound down its India SME operations. Could not compete with Exotel and Ozonetel in product innovation while being squeezed by Jio\'s cloud communication services on pricing.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'BookMyShow (original platform)', sector: 'Entertainment', funding_inr: null, founded_year: 1999, shutdown_date: null, reason: null, failure_tag: null, source_url: null, source_name: null },
  { name: 'PayUMoney', sector: 'FinTech', funding_inr: null, founded_year: 2011, shutdown_date: '2019-01-01', reason: 'Payment gateway for small merchants merged into PayU India, effectively ceasing as a distinct product. The SME payment gateway market was commoditized by Razorpay, Cashfree, and PhonePe for Business. A pioneer that was disrupted by more developer-friendly alternatives.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'EduPristine', sector: 'EdTech', funding_inr: 300, founded_year: 2007, shutdown_date: '2018-01-01', reason: 'Professional education platform for finance and analytics courses that wound down online operations. Could not compete with Coursera, Udemy, and UpGrad\'s better-funded content and marketing. The professional upskilling market required continuous content investment they could not sustain.', failure_tag: 'Market Shift', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Zoomcar (India operations)', sector: 'Transportation', funding_inr: null, founded_year: 2013, shutdown_date: '2024-01-01', reason: 'Self-drive car rental company that went public in the US via SPAC and immediately began collapsing. By 2024, had completely withdrawn from India with no working cars available. The peer-to-peer model never achieved the trust and reliability needed from Indian car owners.', failure_tag: 'Overfunded', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'OLX India (classifieds)', sector: 'E-commerce', funding_inr: null, founded_year: 2006, shutdown_date: '2022-01-01', reason: 'Prosus-backed classifieds platform scaled back aggressively and sold its India autos classifieds to CarTrade. The open classifieds model in India was plagued with fraud and never monetized well. Facebook Marketplace and WhatsApp groups disrupted the model.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Fynd (pre-Reliance)', sector: 'E-commerce', funding_inr: 3500, founded_year: 2012, shutdown_date: '2019-06-01', reason: 'Omnichannel fashion platform acquired by Reliance in 2019. As an independent entity, the company raised $30M but could not achieve the scale needed to compete against Myntra/Ajio. Reliance\'s acquisition gave it survival but ended its startup chapter.', failure_tag: 'Market Shift', source_url: 'https://entrackr.com', source_name: 'Entrackr' },
  { name: 'Power2SME', sector: 'B2B Commerce', funding_inr: 1200, founded_year: 2012, shutdown_date: '2020-01-01', reason: 'B2B raw material marketplace for SMEs that could not scale in India\'s fragmented manufacturing sector. Supply chain digitization for Indian SMEs proved extremely difficult — most preferred personal relationships over platform-based procurement.', failure_tag: 'Too Early', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Junglee (Amazon subsidiary)', sector: 'E-commerce', funding_inr: null, founded_year: 2012, shutdown_date: '2020-07-01', reason: 'Amazon\'s price comparison and shopping site in India shut down in July 2020. With Amazon.in growing strongly, Junglee had become redundant. The standalone comparison shopping model was disrupted by aggregated reviews directly on marketplace pages.', failure_tag: 'Market Shift', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
  { name: 'Hoppr', sector: 'Mobile Apps', funding_inr: 200, founded_year: 2014, shutdown_date: '2017-01-01', reason: 'Personalized content discovery app acquired by Hindustan Times Digital. Never found a working business model — content aggregation proved difficult to monetize without original content. The app was acqui-hired rather than achieving standalone success.', failure_tag: 'Bad Product', source_url: 'https://yourstory.com', source_name: 'YourStory' },
  { name: 'Zomato Gold', sector: 'Food Delivery', funding_inr: null, founded_year: 2018, shutdown_date: '2019-08-01', reason: 'Zomato\'s dining-out subscription program faced revolt from restaurant partners in August 2019. Hundreds of restaurants exited the program simultaneously, calling it unsustainable. Zomato had to completely revamp the program — the original Gold model died.', failure_tag: 'Bad Product', source_url: 'https://economictimes.indiatimes.com', source_name: 'Economic Times' },
]

// Filter out null placeholder entries (they're real companies that didn't fail)
const realFailures = startups.filter(s => s.shutdown_date !== null || s.failure_tag !== null)

async function seed() {
  console.log(`Seeding ${realFailures.length} startups...`)

  // Insert in batches of 50
  const batchSize = 50
  let inserted = 0

  for (let i = 0; i < realFailures.length; i += batchSize) {
    const batch = realFailures.slice(i, i + batchSize)
    const { error } = await supabase.from('startups').insert(batch)
    if (error) {
      console.error('Error inserting batch:', error.message)
    } else {
      inserted += batch.length
      console.log(`Inserted ${inserted}/${realFailures.length}`)
    }
  }

  // Verify count
  const { count } = await supabase.from('startups').select('*', { count: 'exact', head: true })
  console.log(`\n✅ Done. Total startups in DB: ${count}`)
}

seed().catch(console.error)
